# Site settings
title: Recetas
subtitle: Un libro de recetas en Internet
author: Smurf_Dad
email: smurfdad@smurfdad.es
description: > # this means to ignore newlines until "baseurl:"
  Web de recetas de cocina recopiladas por @Smurf_Dad por internet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://recetas.smurfdad.es" # the base hostname & protocol for your site
twitter_username: Smurf_Dad
github_username: smurfdad

# Build settings
markdown: kramdown
paginate_path: page/:num
paginate: 10
show_drafts: false
future: false
permalink: /:year/:month/:title.html
timezone: Europe/Madrid
google-analytics: UA-10059240-2

gems:
  - jekyll-paginate
  - jekyll-sitemap
